const TRIP_PERMISSIONS = Object.freeze({
  VIEW_TRIP: 'VIEW_TRIP',
  MANAGE_ITINERARY: 'MANAGE_ITINERARY',
  INVITE_MEMBERS: 'INVITE_MEMBERS',
  MANAGE_MEMBER_ROLES: 'MANAGE_MEMBER_ROLES',
  COMMENT: 'COMMENT',
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
})

const ROLE_PERMISSION_MATRIX = Object.freeze({
  OWNER: Object.freeze(Object.values(TRIP_PERMISSIONS)),
  EDITOR: Object.freeze([
    TRIP_PERMISSIONS.VIEW_TRIP,
    TRIP_PERMISSIONS.MANAGE_ITINERARY,
    TRIP_PERMISSIONS.INVITE_MEMBERS,
    TRIP_PERMISSIONS.COMMENT,
    TRIP_PERMISSIONS.MANAGE_ORGANIZATION,
  ]),
  VIEWER: Object.freeze([
    TRIP_PERMISSIONS.VIEW_TRIP,
    TRIP_PERMISSIONS.COMMENT,
  ]),
})

const DEFAULT_INVITE_EXPIRY_DAYS = 7
const DEFAULT_PAGE = 1
const DEFAULT_LIMIT = 20
const MAX_LIMIT = 100

export {
  DEFAULT_INVITE_EXPIRY_DAYS,
  DEFAULT_LIMIT,
  DEFAULT_PAGE,
  MAX_LIMIT,
  ROLE_PERMISSION_MATRIX,
  TRIP_PERMISSIONS,
}
